name: release

on:
  push:
    tags:
      - v-*

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
  create_wheels_manylinux:
    runs-on: ubuntu-latest
    name: Create wheels
    steps:
      - uses: actions/checkout@v1
      - name: Build wheels
        working-directory: ./bindings/python
        run: |
          pip install twine wheel
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
